# Header
menu:
  主页: /
  所有文章: /archives
  #标签: /tags
  朋友: /links
  关于: /about

# SubNav
subnav:

  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
    github: "https://github.com/sangmingming"
    weibo: "http://weibo.com/mingmingsang"
    rss: "/atom.xml"
  # facebook: "/"
  # google: "/"
  # twitter: "/"
  #linkedin: "/"
  #github: "#"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png


#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论

avatar: "http://isming.qiniudn.com/my_avatar.jpg"
share: true
duoshuo: "isming"
key: "4b0e75ced77d897a532d6072933c2b51"
#是否开启云标签
#tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
